# FROM johnpapa/angular-cli as angular-built
# Using the above image allows us to skip the angular-cli install
FROM node:8.9-alpine as angular-built
WORKDIR /usr/src/app
RUN npm i -g @angular/cli
COPY package.json package.json
RUN npm install --silent
COPY . .
RUN ng build --prod --build-optimizer
FROM nginx:alpine
LABEL author="John Papa"
COPY --from=angular-built /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80 443
CMD [ "nginx","-g", "daemon off;" ]

# FROM node:0.12

# COPY . /www/app

# RUN npm install -g cordova ionic
# RUN npm install -g bower
# RUN npm install -g gulp

# WORKDIR /www/app
# RUN npm install

# EXPOSE 8100

# ENTRYPOINT ["ionic"]
# CMD ["serve", "8100", "--address", "0.0.0.0"]